apiVersion: v1
kind: ConfigMap
metadata:
  name: url-config
data:
    group_name : Group-25-Bhavin-Tirth
    success_image: s3://finalbucket-bhavin-tirth/finalproj1.png
    fail_image: s3://finalbucket-bhavin-tirth/finalproj1.png   #change Url prior to push