apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-mysql
  namespace: final
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
      app.kubernetes.io/component: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql
        app.kubernetes.io/component: frontend
    spec:
      # serviceAccountName: clo835
      containers:
      - name: simple-webapp-mysql
        image: 037261312162.dkr.ecr.us-east-1.amazonaws.com/finalgroup25-repo:v0.1   #replace URI 
        env:
        - name: Group_Name
          valueFrom:
            configMapKeyRef:
              name: url-config
              key: GROUP_NAME
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 81
        volumeMounts:
        - name: app-secret-volumes
          mountPath: /opt/app-secret-volumes
          readOnly: true
        - name: config-volume
          mountPath: /clo835/config
          readOnly: true
        envFrom:
            - secretRef:
                name: db-secret
      volumes:
      - name: app-secret-volumes
        secret:
          secretName: db-secret
      - name: config-volume
        configMap: 
          name: url-config