apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  selector:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: frontend
  ports:
  - port: 81
    targetPort: 81
  type: NodePort